// Rack-pinion-force steering system generated by JSON.

#include "chrono_vehicle/utils/ChUtilsJSON.h"

#include "src/steering/RackPinionForce.h"

namespace chrono
{
  namespace vehicle
  {

    // -----------------------------------------------------------------------------
    // -----------------------------------------------------------------------------
    RackPinionForce::RackPinionForce(const std::string &filename) : ChRackPinionForce("")
    {
      rapidjson::Document d;
      ReadFileJSON(filename, d);
      if (d.IsNull())
        return;

      Create(d);

      GetLog() << "Loaded JSON: " << filename.c_str() << "\n";
    }

    RackPinionForce::RackPinionForce(const rapidjson::Document &d) : ChRackPinionForce("")
    {
      Create(d);
    }

    void RackPinionForce::Create(const rapidjson::Document &d)
    {
      // Invoke base class method.
      ChPart::Create(d);

      // Read steering link data
      m_steeringLinkMass = d["Steering Link"]["Mass"].GetDouble();
      m_steeringLinkInertia = ReadVectorJSON(d["Steering Link"]["Inertia"]);
      m_steeringLinkCOM = d["Steering Link"]["COM"].GetDouble();
      m_steeringLinkRadius = d["Steering Link"]["Radius"].GetDouble();
      m_steeringLinkLength = d["Steering Link"]["Length"].GetDouble();
      m_damping = d["Steering Link"]["Damping"].GetDouble();

      // Pinion radius
      m_pinionRadius = d["Pinion"]["Radius"].GetDouble();
      m_maxAngle = d["Pinion"]["Maximum Angle (deg)"].GetDouble() * CH_C_DEG_TO_RAD;
    }

  } // end namespace vehicle
} // end namespace chrono
