// Rack-pinion-force steering system generated by JSON.

#include "chrono_vehicle/utils/ChUtilsJSON.h"
#include "chrono/utils/ChConstants.h"

#include <iostream>

#include "src/steering/RackPinionForce.h"

namespace chrono::vehicle
{
  // -----------------------------------------------------------------------------
  // -----------------------------------------------------------------------------
  RackPinionForce::RackPinionForce(const std::string &filename) : ChRackPinionForce("")
  {
    rapidjson::Document d;
    ReadFileJSON(filename, d);
    if (d.IsNull())
      return;

    Create(d);

    std::cout << "Loaded JSON: " << filename << "\n";
  }

  RackPinionForce::RackPinionForce(const rapidjson::Document &d) : ChRackPinionForce("")
  {
    Create(d);
  }

  void RackPinionForce::Create(const rapidjson::Document &d)
  {
    // Invoke base class method.
    ChPart::Create(d);

    // Read steering link data
    m_steeringLinkMass = d["Steering Link"]["Mass"].GetDouble();
    m_steeringLinkInertia = ReadVectorJSON(d["Steering Link"]["Inertia"]);
    m_steeringLinkCOM = d["Steering Link"]["COM"].GetDouble();
    m_steeringLinkRadius = d["Steering Link"]["Radius"].GetDouble();
    m_steeringLinkLength = d["Steering Link"]["Length"].GetDouble();
    m_damping = d["Steering Link"]["Damping"].GetDouble();

    // Pinion radius
    m_pinionRadius = d["Pinion"]["Radius"].GetDouble();

    m_maxAngle = d["Pinion"]["Maximum Angle (deg)"].GetDouble() * CH_DEG_TO_RAD;
  }

} // end namespace chrono::vehicle
